ALTER TABLE inventory_movements
    DROP CONSTRAINT chk_inventory_movements_type,
    DROP CONSTRAINT chk_inventory_movements_type_direction;

ALTER TABLE inventory_movements
    ADD CONSTRAINT chk_inventory_movements_type
        CHECK (type IN (
            'INITIAL_STOCK',
            'MANUAL_ENTRY',
            'MANUAL_EXIT',
            'SALE',
            'RETURN',
            'SALE_RETURN',
            'SALE_CANCELLATION'
        )),
    ADD CONSTRAINT chk_inventory_movements_type_direction
        CHECK (
            (type = 'INITIAL_STOCK' AND direction = 'IN')
            OR (type = 'MANUAL_ENTRY' AND direction = 'IN')
            OR (type = 'MANUAL_EXIT' AND direction = 'OUT')
            OR (type = 'SALE' AND direction = 'OUT')
            OR (type = 'RETURN' AND direction = 'IN')
            OR (type = 'SALE_RETURN' AND direction = 'IN')
            OR (type = 'SALE_CANCELLATION' AND direction = 'IN')
        );

ALTER TABLE cash_movements
    DROP CONSTRAINT chk_cash_movements_type,
    DROP CONSTRAINT chk_cash_movements_type_direction;

ALTER TABLE cash_movements
    ADD CONSTRAINT chk_cash_movements_type
        CHECK (type IN (
            'MANUAL_ENTRY',
            'MANUAL_EXIT',
            'CASH_SALE',
            'RECEIVABLE_PAYMENT',
            'CASH_REFUND',
            'SALE_REFUND',
            'SALE_CANCELLATION_REFUND'
        )),
    ADD CONSTRAINT chk_cash_movements_type_direction
        CHECK (
            (type = 'MANUAL_ENTRY' AND direction = 'INFLOW')
            OR (type = 'MANUAL_EXIT' AND direction = 'OUTFLOW')
            OR (type = 'CASH_SALE' AND direction = 'INFLOW')
            OR (type = 'RECEIVABLE_PAYMENT' AND direction = 'INFLOW')
            OR (type = 'CASH_REFUND' AND direction = 'OUTFLOW')
            OR (type = 'SALE_REFUND' AND direction = 'OUTFLOW')
            OR (type = 'SALE_CANCELLATION_REFUND' AND direction = 'OUTFLOW')
        );

CREATE TABLE sale_cancellations
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id              BIGINT         NOT NULL UNIQUE,
    cash_session_id      BIGINT,
    cancelled_by_user_id BIGINT         NOT NULL,
    reason               VARCHAR(255)   NOT NULL,
    refund_amount        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sale_cancellations_sale
        FOREIGN KEY (sale_id)
            REFERENCES sales (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sale_cancellations_cash_session
        FOREIGN KEY (cash_session_id)
            REFERENCES cash_sessions (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sale_cancellations_cancelled_by_user
        FOREIGN KEY (cancelled_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_sale_cancellations_reason_not_blank
        CHECK (length(trim(reason)) > 0),

    CONSTRAINT chk_sale_cancellations_refund_amount_non_negative
        CHECK (refund_amount >= 0),

    CONSTRAINT chk_sale_cancellations_cash_session_required_for_refund
        CHECK (refund_amount = 0 OR cash_session_id IS NOT NULL)
);

CREATE INDEX idx_sale_cancellations_sale_id ON sale_cancellations (sale_id);
CREATE INDEX idx_sale_cancellations_cash_session_id ON sale_cancellations (cash_session_id);
CREATE INDEX idx_sale_cancellations_cancelled_by_user_id ON sale_cancellations (cancelled_by_user_id);
CREATE INDEX idx_sale_cancellations_created_at ON sale_cancellations (created_at);
