CREATE TABLE suppliers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    contact_name VARCHAR(120),
    phone        VARCHAR(30),
    email        VARCHAR(120),
    notes        VARCHAR(500),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ,

    CONSTRAINT chk_suppliers_name_not_blank
        CHECK (length(trim(name)) > 0)
);

CREATE UNIQUE INDEX uk_suppliers_name_lower ON suppliers (lower(name));
CREATE INDEX idx_suppliers_active ON suppliers (active);

ALTER TABLE products
    ADD COLUMN supplier_id BIGINT,
    ADD CONSTRAINT fk_products_supplier
        FOREIGN KEY (supplier_id)
            REFERENCES suppliers (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;

CREATE INDEX idx_products_supplier_id ON products (supplier_id);

CREATE TABLE supplier_inventory_baselines
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id        BIGINT         NOT NULL,
    baseline_date      DATE           NOT NULL,
    total_sale_value   NUMERIC(12, 2) NOT NULL,
    created_by_user_id BIGINT         NOT NULL,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_supplier_inventory_baselines_supplier
        FOREIGN KEY (supplier_id)
            REFERENCES suppliers (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_inventory_baselines_created_by_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT uk_supplier_inventory_baselines_supplier
        UNIQUE (supplier_id),

    CONSTRAINT chk_supplier_inventory_baselines_total_sale_value_non_negative
        CHECK (total_sale_value >= 0)
);

CREATE TABLE supplier_inventory_baseline_items
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baseline_id         BIGINT         NOT NULL,
    product_id          BIGINT         NOT NULL,
    quantity            NUMERIC(10, 2) NOT NULL,
    sale_price_snapshot NUMERIC(10, 2) NOT NULL,
    inventory_value     NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_supplier_inventory_baseline_items_baseline
        FOREIGN KEY (baseline_id)
            REFERENCES supplier_inventory_baselines (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_inventory_baseline_items_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT uk_supplier_inventory_baseline_items_product
        UNIQUE (baseline_id, product_id),

    CONSTRAINT chk_supplier_inventory_baseline_items_quantity_non_negative
        CHECK (quantity >= 0),

    CONSTRAINT chk_supplier_inventory_baseline_items_sale_price_non_negative
        CHECK (sale_price_snapshot >= 0),

    CONSTRAINT chk_supplier_inventory_baseline_items_inventory_value_math
        CHECK (inventory_value = quantity * sale_price_snapshot)
);

CREATE INDEX idx_supplier_inventory_baseline_items_baseline_product
    ON supplier_inventory_baseline_items (baseline_id, product_id);

CREATE TABLE supplier_entries
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id           BIGINT         NOT NULL,
    entry_date            DATE           NOT NULL,
    registered_by_user_id BIGINT         NOT NULL,
    total_cost            NUMERIC(12, 2) NOT NULL,
    total_sale_value      NUMERIC(12, 2) NOT NULL,
    notes                 VARCHAR(500),
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_supplier_entries_supplier
        FOREIGN KEY (supplier_id)
            REFERENCES suppliers (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_entries_registered_by_user
        FOREIGN KEY (registered_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_supplier_entries_total_cost_non_negative
        CHECK (total_cost >= 0),

    CONSTRAINT chk_supplier_entries_total_sale_value_non_negative
        CHECK (total_sale_value >= 0)
);

CREATE INDEX idx_supplier_entries_supplier_date ON supplier_entries (supplier_id, entry_date);

CREATE TABLE supplier_entry_items
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_entry_id   BIGINT         NOT NULL,
    product_id          BIGINT         NOT NULL,
    quantity            NUMERIC(10, 2) NOT NULL,
    unit_cost           NUMERIC(10, 2) NOT NULL,
    sale_price          NUMERIC(10, 2) NOT NULL,
    cost_subtotal       NUMERIC(12, 2) NOT NULL,
    sale_value_subtotal NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_supplier_entry_items_entry
        FOREIGN KEY (supplier_entry_id)
            REFERENCES supplier_entries (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_entry_items_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT uk_supplier_entry_items_product
        UNIQUE (supplier_entry_id, product_id),

    CONSTRAINT chk_supplier_entry_items_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_supplier_entry_items_unit_cost_non_negative
        CHECK (unit_cost >= 0),

    CONSTRAINT chk_supplier_entry_items_sale_price_positive
        CHECK (sale_price > 0),

    CONSTRAINT chk_supplier_entry_items_cost_math
        CHECK (cost_subtotal = quantity * unit_cost),

    CONSTRAINT chk_supplier_entry_items_sale_value_math
        CHECK (sale_value_subtotal = quantity * sale_price)
);

CREATE INDEX idx_supplier_entry_items_product ON supplier_entry_items (product_id);

CREATE TABLE supplier_settlements
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id               BIGINT         NOT NULL,
    period_start              DATE           NOT NULL,
    period_end                DATE           NOT NULL,
    status                    VARCHAR(20)    NOT NULL,
    opening_inventory_value   NUMERIC(12, 2) NOT NULL,
    entries_sale_value        NUMERIC(12, 2) NOT NULL,
    available_inventory_value NUMERIC(12, 2) NOT NULL,
    closing_inventory_value   NUMERIC(12, 2) NOT NULL,
    expected_amount           NUMERIC(12, 2) NOT NULL,
    delivered_amount          NUMERIC(12, 2),
    difference_amount         NUMERIC(12, 2),
    notes                     VARCHAR(500),
    has_discrepancies         BOOLEAN        NOT NULL DEFAULT FALSE,
    created_by_user_id        BIGINT         NOT NULL,
    finalized_by_user_id      BIGINT,
    created_at                TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at              TIMESTAMPTZ,
    version                   BIGINT         NOT NULL DEFAULT 0,

    CONSTRAINT fk_supplier_settlements_supplier
        FOREIGN KEY (supplier_id)
            REFERENCES suppliers (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_settlements_created_by_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_settlements_finalized_by_user
        FOREIGN KEY (finalized_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_supplier_settlements_status
        CHECK (status IN ('DRAFT', 'FINALIZED')),

    CONSTRAINT chk_supplier_settlements_period
        CHECK (period_end >= period_start),

    CONSTRAINT chk_supplier_settlements_delivered_amount_non_negative
        CHECK (delivered_amount IS NULL OR delivered_amount >= 0)
);

CREATE UNIQUE INDEX uk_supplier_settlements_draft
    ON supplier_settlements (supplier_id)
    WHERE status = 'DRAFT';

CREATE INDEX idx_supplier_settlements_supplier_period_status
    ON supplier_settlements (supplier_id, period_start, period_end, status);

CREATE TABLE supplier_settlement_items
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id         BIGINT         NOT NULL,
    product_id            BIGINT         NOT NULL,
    product_name_snapshot VARCHAR(180)   NOT NULL,
    barcode_snapshot      VARCHAR(50),
    unit_snapshot         VARCHAR(30)    NOT NULL,
    opening_quantity      NUMERIC(10, 2) NOT NULL,
    opening_sale_price    NUMERIC(10, 2) NOT NULL,
    opening_value         NUMERIC(12, 2) NOT NULL,
    received_quantity     NUMERIC(10, 2) NOT NULL,
    received_sale_value   NUMERIC(12, 2) NOT NULL,
    available_quantity    NUMERIC(10, 2) NOT NULL,
    closing_quantity      NUMERIC(10, 2),
    closing_sale_price    NUMERIC(10, 2) NOT NULL,
    closing_value         NUMERIC(12, 2) NOT NULL,
    quantity_to_justify   NUMERIC(10, 2) NOT NULL,
    expected_amount       NUMERIC(12, 2) NOT NULL,
    has_discrepancy       BOOLEAN        NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_supplier_settlement_items_settlement
        FOREIGN KEY (settlement_id)
            REFERENCES supplier_settlements (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_supplier_settlement_items_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT uk_supplier_settlement_items_product
        UNIQUE (settlement_id, product_id),

    CONSTRAINT chk_supplier_settlement_items_name_not_blank
        CHECK (length(trim(product_name_snapshot)) > 0),

    CONSTRAINT chk_supplier_settlement_items_unit
        CHECK (unit_snapshot IN ('PIECE', 'KG', 'LITER', 'PACKAGE')),

    CONSTRAINT chk_supplier_settlement_items_non_negative_quantities
        CHECK (
            opening_quantity >= 0
            AND opening_sale_price >= 0
            AND opening_value >= 0
            AND received_quantity >= 0
            AND received_sale_value >= 0
            AND available_quantity >= 0
            AND (closing_quantity IS NULL OR closing_quantity >= 0)
            AND closing_sale_price >= 0
            AND closing_value >= 0
        )
);

CREATE INDEX idx_supplier_settlement_items_settlement_product
    ON supplier_settlement_items (settlement_id, product_id);

ALTER TABLE inventory_movements
    DROP CONSTRAINT chk_inventory_movements_type,
    DROP CONSTRAINT chk_inventory_movements_type_direction;

ALTER TABLE inventory_movements
    ADD CONSTRAINT chk_inventory_movements_type
        CHECK (type IN (
            'INITIAL_STOCK',
            'MANUAL_ENTRY',
            'MANUAL_EXIT',
            'SALE',
            'RETURN',
            'SALE_RETURN',
            'SALE_CANCELLATION',
            'SUPPLIER_INITIAL_STOCK',
            'SUPPLIER_ENTRY',
            'SUPPLIER_SETTLEMENT_ADJUSTMENT'
        )),
    ADD CONSTRAINT chk_inventory_movements_type_direction
        CHECK (
            (type = 'INITIAL_STOCK' AND direction = 'IN')
            OR (type = 'MANUAL_ENTRY' AND direction = 'IN')
            OR (type = 'MANUAL_EXIT' AND direction = 'OUT')
            OR (type = 'SALE' AND direction = 'OUT')
            OR (type = 'RETURN' AND direction = 'IN')
            OR (type = 'SALE_RETURN' AND direction = 'IN')
            OR (type = 'SALE_CANCELLATION' AND direction = 'IN')
            OR (type = 'SUPPLIER_INITIAL_STOCK' AND direction = 'IN')
            OR (type = 'SUPPLIER_ENTRY' AND direction = 'IN')
            OR (type = 'SUPPLIER_SETTLEMENT_ADJUSTMENT' AND direction IN ('IN', 'OUT'))
        );
