CREATE TABLE legacy_import_sources
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name       VARCHAR(255) NOT NULL,
    file_checksum   VARCHAR(64)  NOT NULL,
    sheet_name      VARCHAR(120) NOT NULL,
    supplier_id     BIGINT       NOT NULL,
    import_status   VARCHAR(30)  NOT NULL,
    imported_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    records_created INTEGER      NOT NULL DEFAULT 0,
    warnings_count  INTEGER      NOT NULL DEFAULT 0,
    error_message   VARCHAR(1000),

    CONSTRAINT fk_legacy_import_sources_supplier
        FOREIGN KEY (supplier_id)
            REFERENCES suppliers (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT uk_legacy_import_sources_file_sheet
        UNIQUE (file_name, file_checksum, sheet_name),

    CONSTRAINT chk_legacy_import_sources_status
        CHECK (import_status IN ('IMPORTED', 'SKIPPED', 'FAILED'))
);

CREATE INDEX idx_legacy_import_sources_supplier_id
    ON legacy_import_sources (supplier_id);

ALTER TABLE supplier_entries
    ADD COLUMN historical_import BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN source_file VARCHAR(255),
    ADD COLUMN source_sheet VARCHAR(120);

ALTER TABLE supplier_settlements
    ADD COLUMN historical_import BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN source_file VARCHAR(255),
    ADD COLUMN source_sheet VARCHAR(120);

CREATE INDEX idx_supplier_entries_historical_import
    ON supplier_entries (historical_import);

CREATE INDEX idx_supplier_settlements_historical_import
    ON supplier_settlements (historical_import);
