CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(30)  NOT NULL DEFAULT 'CASHIER',
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ,

    CONSTRAINT chk_users_role
        CHECK (role IN ('ADMIN', 'CASHIER')),

    CONSTRAINT chk_users_username_not_blank
        CHECK (length(trim(username)) > 0)
);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ,

    CONSTRAINT chk_categories_name_not_blank
        CHECK (length(trim(name)) > 0)
);

CREATE UNIQUE INDEX uk_categories_name_lower
    ON categories (lower(name));

CREATE TABLE products
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   BIGINT         NOT NULL,
    barcode       VARCHAR(50)    NOT NULL UNIQUE,
    name          VARCHAR(180)   NOT NULL,
    description   VARCHAR(255),
    unit          VARCHAR(30)    NOT NULL,
    cost_price    NUMERIC(10, 2) NOT NULL,
    sale_price    NUMERIC(10, 2) NOT NULL,
    current_stock NUMERIC(10, 2) NOT NULL DEFAULT 0,
    minimum_stock NUMERIC(10, 2) NOT NULL DEFAULT 0,
    active        BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_products_name_not_blank
        CHECK (length(trim(name)) > 0),

    CONSTRAINT chk_products_barcode_not_blank
        CHECK (length(trim(barcode)) > 0),

    CONSTRAINT chk_products_unit
        CHECK (unit IN ('PIECE', 'KG', 'LITER', 'PACKAGE')),

    CONSTRAINT chk_products_cost_price_non_negative
        CHECK (cost_price >= 0),

    CONSTRAINT chk_products_sale_price_non_negative
        CHECK (sale_price >= 0),

    CONSTRAINT chk_products_current_stock_non_negative
        CHECK (current_stock >= 0),

    CONSTRAINT chk_products_minimum_stock_non_negative
        CHECK (minimum_stock >= 0)
);

CREATE INDEX idx_products_name ON products (name);
CREATE INDEX idx_products_category_id ON products (category_id);

CREATE TABLE customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(80)  NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    phone      VARCHAR(20),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,

    CONSTRAINT chk_customers_first_name_not_blank
        CHECK (length(trim(first_name)) > 0),

    CONSTRAINT chk_customers_last_name_not_blank
        CHECK (length(trim(last_name)) > 0)
);

CREATE INDEX idx_customers_name ON customers (first_name, last_name);
CREATE INDEX idx_customers_phone ON customers (phone);