CREATE TABLE cash_sessions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opened_by_user_id BIGINT         NOT NULL,
    opening_amount    NUMERIC(10, 2) NOT NULL,
    opened_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status            VARCHAR(20)    NOT NULL DEFAULT 'OPEN',
    closed_by_user_id BIGINT,
    closed_at         TIMESTAMPTZ,
    expected_cash     NUMERIC(10, 2),
    counted_cash      NUMERIC(10, 2),
    cash_difference   NUMERIC(10, 2),

    CONSTRAINT fk_cash_sessions_opened_by_user
        FOREIGN KEY (opened_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_cash_sessions_closed_by_user
        FOREIGN KEY (closed_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_cash_sessions_status
        CHECK (status IN ('OPEN', 'CLOSED')),

    CONSTRAINT chk_cash_sessions_opening_amount_non_negative
        CHECK (opening_amount >= 0),

    CONSTRAINT chk_cash_sessions_expected_cash_non_negative
        CHECK (expected_cash IS NULL OR expected_cash >= 0),

    CONSTRAINT chk_cash_sessions_counted_cash_non_negative
        CHECK (counted_cash IS NULL OR counted_cash >= 0),

    CONSTRAINT chk_cash_sessions_open_fields
        CHECK (
            status <> 'OPEN'
            OR (
                closed_by_user_id IS NULL
                AND closed_at IS NULL
                AND expected_cash IS NULL
                AND counted_cash IS NULL
                AND cash_difference IS NULL
            )
        )
);

CREATE UNIQUE INDEX uk_cash_sessions_open_by_user
    ON cash_sessions (opened_by_user_id)
    WHERE status = 'OPEN';

CREATE INDEX idx_cash_sessions_opened_by_user_id ON cash_sessions (opened_by_user_id);
CREATE INDEX idx_cash_sessions_status ON cash_sessions (status);
CREATE INDEX idx_cash_sessions_opened_at ON cash_sessions (opened_at);
