CREATE TABLE cash_movements
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_session_id    BIGINT          NOT NULL,
    created_by_user_id BIGINT          NOT NULL,
    direction          VARCHAR(20)     NOT NULL,
    type               VARCHAR(40)     NOT NULL,
    amount             NUMERIC(12, 2)  NOT NULL,
    description        VARCHAR(255)    NOT NULL,
    source_type        VARCHAR(40),
    source_id          BIGINT,
    created_at         TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cash_movements_cash_session
        FOREIGN KEY (cash_session_id)
            REFERENCES cash_sessions (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_cash_movements_created_by_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_cash_movements_amount_positive
        CHECK (amount > 0),

    CONSTRAINT chk_cash_movements_description_not_blank
        CHECK (length(trim(description)) > 0),

    CONSTRAINT chk_cash_movements_direction
        CHECK (direction IN ('INFLOW', 'OUTFLOW')),

    CONSTRAINT chk_cash_movements_type
        CHECK (type IN (
            'MANUAL_ENTRY',
            'MANUAL_EXIT',
            'CASH_SALE',
            'RECEIVABLE_PAYMENT',
            'CASH_REFUND'
        )),

    CONSTRAINT chk_cash_movements_type_direction
        CHECK (
            (type = 'MANUAL_ENTRY' AND direction = 'INFLOW')
            OR (type = 'MANUAL_EXIT' AND direction = 'OUTFLOW')
            OR (type = 'CASH_SALE' AND direction = 'INFLOW')
            OR (type = 'RECEIVABLE_PAYMENT' AND direction = 'INFLOW')
            OR (type = 'CASH_REFUND' AND direction = 'OUTFLOW')
        )
);

CREATE INDEX idx_cash_movements_cash_session_id ON cash_movements (cash_session_id);
CREATE INDEX idx_cash_movements_created_by_user_id ON cash_movements (created_by_user_id);
CREATE INDEX idx_cash_movements_created_at ON cash_movements (created_at);
CREATE INDEX idx_cash_movements_direction ON cash_movements (direction);
CREATE INDEX idx_cash_movements_type ON cash_movements (type);
