CREATE TABLE inventory_movements
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT         NOT NULL,
    created_by_user_id BIGINT         NOT NULL,
    direction          VARCHAR(10)    NOT NULL,
    type               VARCHAR(40)    NOT NULL,
    quantity           NUMERIC(10, 2) NOT NULL,
    previous_stock     NUMERIC(10, 2) NOT NULL,
    new_stock          NUMERIC(10, 2) NOT NULL,
    description        VARCHAR(255)   NOT NULL,
    source_type        VARCHAR(40),
    source_id          BIGINT,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_inventory_movements_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_inventory_movements_created_by_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_inventory_movements_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_inventory_movements_previous_stock_non_negative
        CHECK (previous_stock >= 0),

    CONSTRAINT chk_inventory_movements_new_stock_non_negative
        CHECK (new_stock >= 0),

    CONSTRAINT chk_inventory_movements_description_not_blank
        CHECK (length(trim(description)) > 0),

    CONSTRAINT chk_inventory_movements_direction
        CHECK (direction IN ('IN', 'OUT')),

    CONSTRAINT chk_inventory_movements_type
        CHECK (type IN (
            'INITIAL_STOCK',
            'MANUAL_ENTRY',
            'MANUAL_EXIT',
            'SALE',
            'RETURN'
        )),

    CONSTRAINT chk_inventory_movements_type_direction
        CHECK (
            (type = 'INITIAL_STOCK' AND direction = 'IN')
            OR (type = 'MANUAL_ENTRY' AND direction = 'IN')
            OR (type = 'MANUAL_EXIT' AND direction = 'OUT')
            OR (type = 'SALE' AND direction = 'OUT')
            OR (type = 'RETURN' AND direction = 'IN')
        ),

    CONSTRAINT chk_inventory_movements_stock_math
        CHECK (
            (direction = 'IN' AND new_stock = previous_stock + quantity)
            OR (direction = 'OUT' AND new_stock = previous_stock - quantity)
        ),

    CONSTRAINT chk_inventory_movements_source_pair
        CHECK (
            (source_type IS NULL AND source_id IS NULL)
            OR (source_type IS NOT NULL AND source_id IS NOT NULL)
        ),

    CONSTRAINT chk_inventory_movements_manual_source_null
        CHECK (
            type NOT IN ('MANUAL_ENTRY', 'MANUAL_EXIT')
            OR (source_type IS NULL AND source_id IS NULL)
        )
);

CREATE INDEX idx_inventory_movements_product_id ON inventory_movements (product_id);
CREATE INDEX idx_inventory_movements_created_by_user_id ON inventory_movements (created_by_user_id);
CREATE INDEX idx_inventory_movements_created_at ON inventory_movements (created_at);
CREATE INDEX idx_inventory_movements_direction ON inventory_movements (direction);
CREATE INDEX idx_inventory_movements_type ON inventory_movements (type);
CREATE INDEX idx_inventory_movements_source ON inventory_movements (source_type, source_id);
