CREATE TABLE sales
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_session_id    BIGINT         NOT NULL,
    created_by_user_id BIGINT         NOT NULL,
    customer_id        BIGINT,
    sale_type          VARCHAR(20)    NOT NULL,
    status             VARCHAR(20)    NOT NULL,
    total              NUMERIC(12, 2) NOT NULL,
    cash_received      NUMERIC(12, 2) NOT NULL,
    change_amount      NUMERIC(12, 2) NOT NULL,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at       TIMESTAMPTZ,

    CONSTRAINT fk_sales_cash_session
        FOREIGN KEY (cash_session_id)
            REFERENCES cash_sessions (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sales_created_by_user
        FOREIGN KEY (created_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sales_customer
        FOREIGN KEY (customer_id)
            REFERENCES customers (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_sales_sale_type
        CHECK (sale_type IN ('CASH', 'CREDIT')),

    CONSTRAINT chk_sales_status
        CHECK (status IN ('COMPLETED', 'CANCELLED')),

    CONSTRAINT chk_sales_total_positive
        CHECK (total > 0),

    CONSTRAINT chk_sales_cash_received_covers_cash_sale
        CHECK (sale_type <> 'CASH' OR cash_received >= total),

    CONSTRAINT chk_sales_change_amount_math
        CHECK (change_amount = cash_received - total),

    CONSTRAINT chk_sales_completed_not_cancelled
        CHECK (status <> 'COMPLETED' OR cancelled_at IS NULL)
);

CREATE TABLE sale_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id         BIGINT         NOT NULL,
    product_id      BIGINT         NOT NULL,
    product_name    VARCHAR(180)   NOT NULL,
    product_barcode VARCHAR(50)    NOT NULL,
    product_unit    VARCHAR(30)    NOT NULL,
    quantity        NUMERIC(10, 2) NOT NULL,
    unit_price      NUMERIC(12, 2) NOT NULL,
    unit_cost       NUMERIC(12, 2) NOT NULL,
    line_total      NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_sale_items_sale
        FOREIGN KEY (sale_id)
            REFERENCES sales (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sale_items_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_sale_items_product_name_not_blank
        CHECK (length(trim(product_name)) > 0),

    CONSTRAINT chk_sale_items_product_barcode_not_blank
        CHECK (length(trim(product_barcode)) > 0),

    CONSTRAINT chk_sale_items_product_unit
        CHECK (product_unit IN ('PIECE', 'KG', 'LITER', 'PACKAGE')),

    CONSTRAINT chk_sale_items_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_sale_items_unit_price_non_negative
        CHECK (unit_price >= 0),

    CONSTRAINT chk_sale_items_unit_cost_non_negative
        CHECK (unit_cost >= 0),

    CONSTRAINT chk_sale_items_line_total_positive
        CHECK (line_total > 0),

    CONSTRAINT chk_sale_items_line_total_math
        CHECK (line_total = quantity * unit_price)
);

CREATE INDEX idx_sales_cash_session_id ON sales (cash_session_id);
CREATE INDEX idx_sales_created_by_user_id ON sales (created_by_user_id);
CREATE INDEX idx_sales_customer_id ON sales (customer_id);
CREATE INDEX idx_sales_status ON sales (status);
CREATE INDEX idx_sales_created_at ON sales (created_at);

CREATE INDEX idx_sale_items_sale_id ON sale_items (sale_id);
CREATE INDEX idx_sale_items_product_id ON sale_items (product_id);
