ALTER TABLE sales
    ALTER COLUMN cash_received DROP NOT NULL,
    ALTER COLUMN change_amount DROP NOT NULL;

ALTER TABLE sales
    DROP CONSTRAINT chk_sales_cash_received_covers_cash_sale,
    DROP CONSTRAINT chk_sales_change_amount_math;

ALTER TABLE sales
    ADD CONSTRAINT chk_sales_payment_fields_by_type
        CHECK (
            (
                sale_type = 'CASH'
                AND cash_received IS NOT NULL
                AND change_amount IS NOT NULL
                AND cash_received >= total
                AND change_amount = cash_received - total
            )
            OR (
                sale_type = 'CREDIT'
                AND customer_id IS NOT NULL
                AND cash_received IS NULL
                AND change_amount IS NULL
            )
        );

CREATE TABLE receivables
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id             BIGINT         NOT NULL UNIQUE,
    customer_id         BIGINT         NOT NULL,
    original_amount     NUMERIC(12, 2) NOT NULL,
    paid_amount         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    outstanding_balance NUMERIC(12, 2) NOT NULL,
    status              VARCHAR(30)    NOT NULL,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at             TIMESTAMPTZ,

    CONSTRAINT fk_receivables_sale
        FOREIGN KEY (sale_id)
            REFERENCES sales (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_receivables_customer
        FOREIGN KEY (customer_id)
            REFERENCES customers (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_receivables_status
        CHECK (status IN ('PENDING', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')),

    CONSTRAINT chk_receivables_original_amount_positive
        CHECK (original_amount > 0),

    CONSTRAINT chk_receivables_paid_amount_non_negative
        CHECK (paid_amount >= 0),

    CONSTRAINT chk_receivables_paid_amount_not_greater_than_original
        CHECK (paid_amount <= original_amount),

    CONSTRAINT chk_receivables_outstanding_balance_non_negative
        CHECK (outstanding_balance >= 0),

    CONSTRAINT chk_receivables_balance_math
        CHECK (outstanding_balance = original_amount - paid_amount),

    CONSTRAINT chk_receivables_pending_fields
        CHECK (
            status <> 'PENDING'
            OR (
                paid_amount = 0
                AND outstanding_balance = original_amount
                AND paid_at IS NULL
            )
        ),

    CONSTRAINT chk_receivables_paid_fields
        CHECK (
            status <> 'PAID'
            OR (
                outstanding_balance = 0
                AND paid_at IS NOT NULL
            )
        )
);

CREATE INDEX idx_receivables_customer_id ON receivables (customer_id);
CREATE INDEX idx_receivables_status ON receivables (status);
CREATE INDEX idx_receivables_created_at ON receivables (created_at);
