CREATE TABLE receivable_payments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receivable_id       BIGINT          NOT NULL,
    cash_session_id     BIGINT          NOT NULL,
    received_by_user_id BIGINT          NOT NULL,
    amount              NUMERIC(12, 2)  NOT NULL,
    notes               VARCHAR(255),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_receivable_payments_receivable
        FOREIGN KEY (receivable_id)
            REFERENCES receivables (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_receivable_payments_cash_session
        FOREIGN KEY (cash_session_id)
            REFERENCES cash_sessions (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_receivable_payments_received_by_user
        FOREIGN KEY (received_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_receivable_payments_amount_positive
        CHECK (amount > 0)
);

CREATE INDEX idx_receivable_payments_receivable_id ON receivable_payments (receivable_id);
CREATE INDEX idx_receivable_payments_cash_session_id ON receivable_payments (cash_session_id);
CREATE INDEX idx_receivable_payments_received_by_user_id ON receivable_payments (received_by_user_id);
CREATE INDEX idx_receivable_payments_created_at ON receivable_payments (created_at);
