ALTER TABLE sales
    DROP CONSTRAINT chk_sales_status;

ALTER TABLE sales
    ADD CONSTRAINT chk_sales_status
        CHECK (status IN ('COMPLETED', 'PARTIALLY_RETURNED', 'RETURNED', 'CANCELLED'));

ALTER TABLE sale_items
    ADD COLUMN returned_quantity NUMERIC(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE sale_items
    ADD CONSTRAINT chk_sale_items_returned_quantity_non_negative
        CHECK (returned_quantity >= 0),
    ADD CONSTRAINT chk_sale_items_returned_quantity_not_greater_than_quantity
        CHECK (returned_quantity <= quantity);

ALTER TABLE receivables
    ADD COLUMN returned_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN adjusted_amount NUMERIC(12, 2);

UPDATE receivables
SET adjusted_amount = original_amount
WHERE adjusted_amount IS NULL;

ALTER TABLE receivables
    ALTER COLUMN adjusted_amount SET NOT NULL;

ALTER TABLE receivables
    DROP CONSTRAINT chk_receivables_paid_amount_not_greater_than_original,
    DROP CONSTRAINT chk_receivables_balance_math,
    DROP CONSTRAINT chk_receivables_pending_fields,
    DROP CONSTRAINT chk_receivables_paid_fields;

ALTER TABLE receivables
    ADD CONSTRAINT chk_receivables_returned_amount_non_negative
        CHECK (returned_amount >= 0),
    ADD CONSTRAINT chk_receivables_returned_amount_not_greater_than_original
        CHECK (returned_amount <= original_amount),
    ADD CONSTRAINT chk_receivables_adjusted_amount_non_negative
        CHECK (adjusted_amount >= 0),
    ADD CONSTRAINT chk_receivables_adjusted_amount_math
        CHECK (adjusted_amount = original_amount - returned_amount),
    ADD CONSTRAINT chk_receivables_paid_amount_not_greater_than_adjusted
        CHECK (paid_amount <= adjusted_amount),
    ADD CONSTRAINT chk_receivables_balance_math
        CHECK (outstanding_balance = adjusted_amount - paid_amount),
    ADD CONSTRAINT chk_receivables_pending_fields
        CHECK (
            status <> 'PENDING'
            OR (
                paid_amount = 0
                AND outstanding_balance = adjusted_amount
                AND adjusted_amount > 0
                AND paid_at IS NULL
            )
        ),
    ADD CONSTRAINT chk_receivables_paid_fields
        CHECK (
            status <> 'PAID'
            OR (
                adjusted_amount > 0
                AND outstanding_balance = 0
                AND paid_at IS NOT NULL
            )
        ),
    ADD CONSTRAINT chk_receivables_cancelled_fields
        CHECK (
            status <> 'CANCELLED'
            OR (
                adjusted_amount = 0
                AND paid_amount = 0
                AND outstanding_balance = 0
                AND paid_at IS NULL
            )
        );

ALTER TABLE inventory_movements
    DROP CONSTRAINT chk_inventory_movements_type,
    DROP CONSTRAINT chk_inventory_movements_type_direction;

ALTER TABLE inventory_movements
    ADD CONSTRAINT chk_inventory_movements_type
        CHECK (type IN (
            'INITIAL_STOCK',
            'MANUAL_ENTRY',
            'MANUAL_EXIT',
            'SALE',
            'RETURN',
            'SALE_RETURN'
        )),
    ADD CONSTRAINT chk_inventory_movements_type_direction
        CHECK (
            (type = 'INITIAL_STOCK' AND direction = 'IN')
            OR (type = 'MANUAL_ENTRY' AND direction = 'IN')
            OR (type = 'MANUAL_EXIT' AND direction = 'OUT')
            OR (type = 'SALE' AND direction = 'OUT')
            OR (type = 'RETURN' AND direction = 'IN')
            OR (type = 'SALE_RETURN' AND direction = 'IN')
        );

ALTER TABLE cash_movements
    DROP CONSTRAINT chk_cash_movements_type,
    DROP CONSTRAINT chk_cash_movements_type_direction;

ALTER TABLE cash_movements
    ADD CONSTRAINT chk_cash_movements_type
        CHECK (type IN (
            'MANUAL_ENTRY',
            'MANUAL_EXIT',
            'CASH_SALE',
            'RECEIVABLE_PAYMENT',
            'CASH_REFUND',
            'SALE_REFUND'
        )),
    ADD CONSTRAINT chk_cash_movements_type_direction
        CHECK (
            (type = 'MANUAL_ENTRY' AND direction = 'INFLOW')
            OR (type = 'MANUAL_EXIT' AND direction = 'OUTFLOW')
            OR (type = 'CASH_SALE' AND direction = 'INFLOW')
            OR (type = 'RECEIVABLE_PAYMENT' AND direction = 'INFLOW')
            OR (type = 'CASH_REFUND' AND direction = 'OUTFLOW')
            OR (type = 'SALE_REFUND' AND direction = 'OUTFLOW')
        );

CREATE TABLE sale_returns
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id              BIGINT         NOT NULL,
    cash_session_id      BIGINT,
    processed_by_user_id BIGINT         NOT NULL,
    total_amount         NUMERIC(12, 2) NOT NULL,
    cash_refund_amount   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    reason               VARCHAR(255)   NOT NULL,
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sale_returns_sale
        FOREIGN KEY (sale_id)
            REFERENCES sales (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sale_returns_cash_session
        FOREIGN KEY (cash_session_id)
            REFERENCES cash_sessions (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sale_returns_processed_by_user
        FOREIGN KEY (processed_by_user_id)
            REFERENCES users (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_sale_returns_total_amount_positive
        CHECK (total_amount > 0),

    CONSTRAINT chk_sale_returns_cash_refund_amount_non_negative
        CHECK (cash_refund_amount >= 0),

    CONSTRAINT chk_sale_returns_cash_refund_amount_not_greater_than_total
        CHECK (cash_refund_amount <= total_amount),

    CONSTRAINT chk_sale_returns_reason_not_blank
        CHECK (length(trim(reason)) > 0),

    CONSTRAINT chk_sale_returns_cash_session_required_for_refund
        CHECK (cash_refund_amount = 0 OR cash_session_id IS NOT NULL)
);

CREATE TABLE sale_return_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_id BIGINT         NOT NULL,
    sale_item_id   BIGINT         NOT NULL,
    product_id     BIGINT         NOT NULL,
    quantity       NUMERIC(10, 2) NOT NULL,
    unit_price     NUMERIC(12, 2) NOT NULL,
    subtotal       NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_sale_return_items_sale_return
        FOREIGN KEY (sale_return_id)
            REFERENCES sale_returns (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sale_return_items_sale_item
        FOREIGN KEY (sale_item_id)
            REFERENCES sale_items (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT fk_sale_return_items_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    CONSTRAINT chk_sale_return_items_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_sale_return_items_unit_price_non_negative
        CHECK (unit_price >= 0),

    CONSTRAINT chk_sale_return_items_subtotal_non_negative
        CHECK (subtotal >= 0),

    CONSTRAINT uq_sale_return_items_return_sale_item
        UNIQUE (sale_return_id, sale_item_id)
);

CREATE INDEX idx_sale_returns_sale_id ON sale_returns (sale_id);
CREATE INDEX idx_sale_returns_cash_session_id ON sale_returns (cash_session_id);
CREATE INDEX idx_sale_returns_processed_by_user_id ON sale_returns (processed_by_user_id);
CREATE INDEX idx_sale_returns_created_at ON sale_returns (created_at);

CREATE INDEX idx_sale_return_items_sale_return_id ON sale_return_items (sale_return_id);
CREATE INDEX idx_sale_return_items_sale_item_id ON sale_return_items (sale_item_id);
CREATE INDEX idx_sale_return_items_product_id ON sale_return_items (product_id);
