export const ROUTE_PATHS = {
  login: '/login',
  changePassword: '/change-password',
  dashboard: '/dashboard',
  cashSessionOpen: '/cash-session/open',
  cashMovements: '/cash/movements',
  cashSessionsHistory: '/cash/sessions',
  inventoryMovements: '/inventory/movements',
  categories: '/catalog/categories',
  products: '/catalog/products',
  customers: '/customers',
  sales: '/sales',
  salesHistory: '/sales/history',
  receivables: '/receivables',
  customerAccountReceivable: '/sales/accounts-receivable/customers/:customerId',
  users: '/users',
} as const
