export const ROUTE_PATHS = {
  login: '/login',
  changePassword: '/change-password',
  dashboard: '/dashboard',
  cashSessionOpen: '/cash-session/open',
  cashMovements: '/cash/movements',
  cashSessionsHistory: '/cash/sessions',
  inventoryMovements: '/inventory/movements',
  categories: '/catalog/categories',
  products: '/catalog/products',
  suppliers: '/suppliers',
  supplierInventoryBaseline: '/suppliers/:supplierId/inventory-baseline',
  supplierEntries: '/inventory/supplier-entries',
  supplierEntriesCreate: '/inventory/supplier-entries/new',
  supplierEntryDetails: '/inventory/supplier-entries/:entryId',
  supplierSettlementCreate: '/inventory/supplier-settlements/new',
  supplierSettlementEdit: '/inventory/supplier-settlements/:settlementId/edit',
  supplierSettlementDetails: '/inventory/supplier-settlements/:settlementId',
  supplierSettlements: '/inventory/supplier-settlements',
  customers: '/customers',
  sales: '/sales',
  salesHistory: '/sales/history',
  receivables: '/receivables',
  reports: '/reports',
  customerAccountReceivable: '/sales/accounts-receivable/customers/:customerId',
  users: '/users',
} as const
